local C = {}

C.AssetConversion = {
  ["9C0979A079AB586E48AF435B2A7C9AE594C3DC04"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/9C0979A079AB586E48AF435B2A7C9AE594C3DC04.jpg",
  ["29F86901FC22B8CE31E4492ACE04FBF5FE9AFA20"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/29F86901FC22B8CE31E4492ACE04FBF5FE9AFA20.jpg",
  ["2B19802085F358058395C54D0593A6FDD896E0C0"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/2B19802085F358058395C54D0593A6FDD896E0C0.png",
  ["3AD1274013C24B49313D0B053AEFFDC48225749D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3AD1274013C24B49313D0B053AEFFDC48225749D.png",
  ["6E228A2D55B55997A24517ED21FB609992E11B6C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6E228A2D55B55997A24517ED21FB609992E11B6C.png",
  ["50C3A25B93E2C3764E447AFAFCF9291F5ED4610A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/50C3A25B93E2C3764E447AFAFCF9291F5ED4610A.png",
  ["7699DDBB0D49FEE5B96ADDA93F6DD7FD75C95770"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7699DDBB0D49FEE5B96ADDA93F6DD7FD75C95770.png",
  ["259024C45BA0D08C6049E6EE106B6B6EEBA84C99"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/259024C45BA0D08C6049E6EE106B6B6EEBA84C99.png",
  ["951304B4758CA987328B47FAB6A5D379F53F616C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/951304B4758CA987328B47FAB6A5D379F53F616C.png",
  ["6854110C2DD76F17931F7E85386A1567298489E2"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6854110C2DD76F17931F7E85386A1567298489E2.png",
  ["A7540C39C63BB155A0D33080D035EFFD2C622BD9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A7540C39C63BB155A0D33080D035EFFD2C622BD9.png",
  ["C095B1DEAA5E699507756A6A58F493E7B851845E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C095B1DEAA5E699507756A6A58F493E7B851845E.png",
  ["C0183D4173FE99E336E5D95B43D4906FF0C19D2A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C0183D4173FE99E336E5D95B43D4906FF0C19D2A.png",
  ["C877F2B1586727C0866D8F0D97BB4E49C74C79D4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C877F2B1586727C0866D8F0D97BB4E49C74C79D4.png",
  ["D45AF1D376983231BAB69299ACC63294DCDB7C16"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/D45AF1D376983231BAB69299ACC63294DCDB7C16.png",
  ["DA531BE28D2E1176BD22D834122B620F4D4DE6E9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DA531BE28D2E1176BD22D834122B620F4D4DE6E9.png",
  ["E1560F9C6722C94A3ED0107EBF9FF18F9BBC90D8"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E1560F9C6722C94A3ED0107EBF9FF18F9BBC90D8.png",
  ["F904EC1B8C4EABAE4450FC8433B80E98C38D1271"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F904EC1B8C4EABAE4450FC8433B80E98C38D1271.png",
  ["F1858706D68FF9872594BA3BDFE1BBD1485E4F79"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F1858706D68FF9872594BA3BDFE1BBD1485E4F79.png",
  ["2BA9D7CB61A6CC3B3BAFC2DEE20F32926896C300"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/2BA9D7CB61A6CC3B3BAFC2DEE20F32926896C300.jpg",
  ["5E4DC95672CCE3228559ED718F79C6AE4855F180"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/5E4DC95672CCE3228559ED718F79C6AE4855F180.jpg",
  ["6A4B87888879644C493437316A6B402E64D35F37"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6A4B87888879644C493437316A6B402E64D35F37.jpg",
  ["6A8AF66383C290A86A34A0D708AB49E70087F954"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6A8AF66383C290A86A34A0D708AB49E70087F954.jpg",
  ["08EFFCB9787B2EF20B8D0F829E4EC6BC1A8C9D00"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/08EFFCB9787B2EF20B8D0F829E4EC6BC1A8C9D00.jpg",
  ["28E034F3ADE22F44B0F6154725774860C61122DB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/28E034F3ADE22F44B0F6154725774860C61122DB.jpg",
  ["48BDC866C3489A85E80AB9D81E707BC94C9A1025"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/48BDC866C3489A85E80AB9D81E707BC94C9A1025.jpg",
  ["508DA3C602CAF2CF2FA9B9B9A921985AC9200EBF"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/508DA3C602CAF2CF2FA9B9B9A921985AC9200EBF.jpg",
  ["3168D931DCE8AB01FF41BA130B1C3850A1869931"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3168D931DCE8AB01FF41BA130B1C3850A1869931.jpg",
  ["8156EB20FD4931DD0188FFBE1C75AA055359BB8C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/8156EB20FD4931DD0188FFBE1C75AA055359BB8C.jpg",
  ["470168F88421F4C91F644CED815A5458E661E570"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/470168F88421F4C91F644CED815A5458E661E570.jpg",
  ["854178DB3477E069648AD47FD0C1293BB9EB2DF4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/854178DB3477E069648AD47FD0C1293BB9EB2DF4.jpg",
  ["965270732C966B4CA84D327BC075F041924E3AF5"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/965270732C966B4CA84D327BC075F041924E3AF5.jpg",
  ["74038608486820579098EC0F6C10C0894D865A31"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/74038608486820579098EC0F6C10C0894D865A31.jpg",
  ["A55DF69D1CD0AB803CC458E8EBE56F112716AFF9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A55DF69D1CD0AB803CC458E8EBE56F112716AFF9.jpg",
  ["B2B9F6DB63D4A493A88D700C2CBD1ACDDB9A234E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B2B9F6DB63D4A493A88D700C2CBD1ACDDB9A234E.jpg",
  ["BDFB874F4DA93B5C26ABC3BBE076C4345279638D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/BDFB874F4DA93B5C26ABC3BBE076C4345279638D.jpg",
  ["C1266F4DEACED21FC29FBE1C5F9F367ADCA07DB0"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C1266F4DEACED21FC29FBE1C5F9F367ADCA07DB0.jpg",
  ["CB96A2D3DE315CC816E18404529C673E4D07EFDD"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CB96A2D3DE315CC816E18404529C673E4D07EFDD.jpg",
  ["E28BC85AA3AD12A51580274DE44D0FBD98C38604"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E28BC85AA3AD12A51580274DE44D0FBD98C38604.jpg",
  ["E56CD09D202832C8E8D9EDB65F697FA2B159DAC3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E56CD09D202832C8E8D9EDB65F697FA2B159DAC3.jpg",
  ["EE53B037F263B08598D4233734A489E78BB3CCAE"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/EE53B037F263B08598D4233734A489E78BB3CCAE.jpg",
  ["F1E0CB33FAC9369A492AE74243FA653CD6641E5B"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F1E0CB33FAC9369A492AE74243FA653CD6641E5B.jpg",
  ["F14465CFF771906FD0EC010BAC00BD5F45CE69FA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F14465CFF771906FD0EC010BAC00BD5F45CE69FA.jpg",
  ["938108FE499DAFBF774D140D618453533C1487CB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/938108FE499DAFBF774D140D618453533C1487CB.png",
  ["35EB76683156DD6AC83DE4BA06E7E7CFD59C29F5"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/35EB76683156DD6AC83DE4BA06E7E7CFD59C29F5.jpg",
  ["F1C341BBCBAD16CBD06F37EFBC3DCD1C931672CB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F1C341BBCBAD16CBD06F37EFBC3DCD1C931672CB.jpg",
  ["0B5B4E57F87540CE98D89D7ACC3CC8C1DC6AD8B4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0B5B4E57F87540CE98D89D7ACC3CC8C1DC6AD8B4.jpg",
  ["0C5EA275C895CD90A029CCCA913058AA101750D4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0C5EA275C895CD90A029CCCA913058AA101750D4.jpg",
  ["0CE475DA86213CD189565A5FF3541E9509FF724C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0CE475DA86213CD189565A5FF3541E9509FF724C.jpg",
  ["0D8DD523608E72B53AFBDD3C702C396A77696F54"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0D8DD523608E72B53AFBDD3C702C396A77696F54.jpg",
  ["0E0100033743743F7E489916C42448F356013870"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0E0100033743743F7E489916C42448F356013870.jpg",
  ["0FDB3EC9B33B6D97638B39BE23C9CBE6925BA1A1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0FDB3EC9B33B6D97638B39BE23C9CBE6925BA1A1.jpg",
  ["1A4C5DEFEAA73904DBD537ED6135BA874F031FA3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1A4C5DEFEAA73904DBD537ED6135BA874F031FA3.jpg",
  ["1AD8369D21C9DF0A2EFAF048B0218F1E7C97BDE9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1AD8369D21C9DF0A2EFAF048B0218F1E7C97BDE9.jpg",
  ["1E2139C5EF223CC43D2E1E84380C9D919C4708AB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1E2139C5EF223CC43D2E1E84380C9D919C4708AB.jpg",
  ["1EC7353C5E9E018E0E0F2EFFFBA1D457EEAB1D0B"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1EC7353C5E9E018E0E0F2EFFFBA1D457EEAB1D0B.jpg",
  ["1FDB25E5D004D45D2B625C83D09FE5D9C3673288"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1FDB25E5D004D45D2B625C83D09FE5D9C3673288.jpg",
  ["02E4260B45FB3FDFDB24D5E2C5D1023630869C95"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/02E4260B45FB3FDFDB24D5E2C5D1023630869C95.jpg",
  ["2AFDA41874C5D0AA20BEB4D0901DBBCFD079BE53"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/2AFDA41874C5D0AA20BEB4D0901DBBCFD079BE53.jpg",
  ["2C70B53728C7880BB4DAD3DC936F86EEC85FD481"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/2C70B53728C7880BB4DAD3DC936F86EEC85FD481.jpg",
  ["3B49B46E2CCAA5C9953D4977EA70938B146A275F"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3B49B46E2CCAA5C9953D4977EA70938B146A275F.jpg",
  ["3D9D04DD065D9AB826F75D69DCC8DC5EF9E524C6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3D9D04DD065D9AB826F75D69DCC8DC5EF9E524C6.jpg",
  ["3D3537FC18B5AD1A149FB66B1828FC8815357D71"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3D3537FC18B5AD1A149FB66B1828FC8815357D71.jpg",
  ["3F7975491E8C1A8CD7175F8218D0BE8ECDAF4EA3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3F7975491E8C1A8CD7175F8218D0BE8ECDAF4EA3.jpg",
  ["4AADEA78E63594DAF0B352A35D30C31EBDC80CF7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4AADEA78E63594DAF0B352A35D30C31EBDC80CF7.jpg",
  ["4AF13EFFB3954A9BF838B9F805831B8EAA8544AE"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4AF13EFFB3954A9BF838B9F805831B8EAA8544AE.jpg",
  ["4BDC7E6A21682ADECDB4308BCD489E9036859A1F"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4BDC7E6A21682ADECDB4308BCD489E9036859A1F.jpg",
  ["4CC1A15069DD4FBF178E219E5476825BD6619DCF"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4CC1A15069DD4FBF178E219E5476825BD6619DCF.jpg",
  ["4D06D343E874A894576FBF61C5DE96B34B1D0405"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4D06D343E874A894576FBF61C5DE96B34B1D0405.jpg",
  ["4E5FC15E09D9828F117CFA2D363294CCFFF85DBE"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4E5FC15E09D9828F117CFA2D363294CCFFF85DBE.jpg",
  ["4EE9E3FBAC3A36179C8A9EBEB98F3A5A38D110BA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4EE9E3FBAC3A36179C8A9EBEB98F3A5A38D110BA.jpg",
  ["4F6CA4123C4191E54F0E036D3E111936213611AA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4F6CA4123C4191E54F0E036D3E111936213611AA.jpg",
  ["4FEDB5275913F1AD2EE4FD3228B6AA87051B2F12"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4FEDB5275913F1AD2EE4FD3228B6AA87051B2F12.jpg",
  ["5BF9FD9ED60A40FE1CC11C84F37CE7C541F5FA6C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/5BF9FD9ED60A40FE1CC11C84F37CE7C541F5FA6C.jpg",
  ["5C4341AABABDE61E86C4C7DCA1B2CC09F8E60D24"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/5C4341AABABDE61E86C4C7DCA1B2CC09F8E60D24.jpg",
  ["5D5816F9AD4DC01F39F6B90327439477B27C758B"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/5D5816F9AD4DC01F39F6B90327439477B27C758B.jpg",
  ["5ED3AA9D8D5DDA5438F55993E54CF7293290DB4A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/5ED3AA9D8D5DDA5438F55993E54CF7293290DB4A.jpg",
  ["6AD7243AA53ED355CC4F0AC1B61A98A3BCA75009"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6AD7243AA53ED355CC4F0AC1B61A98A3BCA75009.jpg",
  ["6B8123F696E332AA529B48462E4C69D7F34AB260"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6B8123F696E332AA529B48462E4C69D7F34AB260.jpg",
  ["6C0BE95FD7A556ACFB445CA1CB0A264FEB1C6DAB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6C0BE95FD7A556ACFB445CA1CB0A264FEB1C6DAB.jpg",
  ["6ECEE094A664C62B4874CD0373197AF452174051"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6ECEE094A664C62B4874CD0373197AF452174051.jpg",
  ["7AE98B077F7D6B749F7EA950CE2A94A3847E09C0"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7AE98B077F7D6B749F7EA950CE2A94A3847E09C0.jpg",
  ["7BE9256C1AC09BF250F4EB03106AE32958799FE4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7BE9256C1AC09BF250F4EB03106AE32958799FE4.jpg",
  ["7C33AED41527D9830B088D0B10B4E7B8274345CE"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7C33AED41527D9830B088D0B10B4E7B8274345CE.jpg",
  ["7D10AB50D8784116112319B36D670371FEB5622C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7D10AB50D8784116112319B36D670371FEB5622C.jpg",
  ["7D98E791B02C7E08148CD9C741918D264A2972D9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7D98E791B02C7E08148CD9C741918D264A2972D9.jpg",
  ["7EA4F88B2567C678CD94DC7FB2A46976491E3114"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7EA4F88B2567C678CD94DC7FB2A46976491E3114.jpg",
  ["7FB79363111401CED3BAFF2D052C407EFA593F60"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7FB79363111401CED3BAFF2D052C407EFA593F60.jpg",
  ["8A1D20CD765CA4133CE439CAD3B5446E73E1A73E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/8A1D20CD765CA4133CE439CAD3B5446E73E1A73E.jpg",
  ["8B810AA31FD4DB4C7D1918DD424798560A4663C1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/8B810AA31FD4DB4C7D1918DD424798560A4663C1.jpg",
  ["8DF6334F5CD44A7B9BB1E0442BBD4638F8318D39"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/8DF6334F5CD44A7B9BB1E0442BBD4638F8318D39.jpg",
  ["8EECBCF540CC40C143E698BC853AD815EB647D0B"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/8EECBCF540CC40C143E698BC853AD815EB647D0B.jpg",
  ["8F4DCA0AA9A893B29084AE972BD9B3B559CA9BBB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/8F4DCA0AA9A893B29084AE972BD9B3B559CA9BBB.jpg",
  ["009DE311A35486C0F4B345C4FC47BC0F2F086616"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/009DE311A35486C0F4B345C4FC47BC0F2F086616.jpg",
  ["09C588C597D035F69FD03D135488982AC48BC373"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/09C588C597D035F69FD03D135488982AC48BC373.jpg",
  ["09D39A4A8BEEFF7B031164C0AAD70305D6DED4C1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/09D39A4A8BEEFF7B031164C0AAD70305D6DED4C1.jpg",
  ["9A7880710A4C9FD935C0105A8220BCFA682EC853"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/9A7880710A4C9FD935C0105A8220BCFA682EC853.jpg",
  ["9B35C81D249FAFCFD557CCFC73C7C9871623D149"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/9B35C81D249FAFCFD557CCFC73C7C9871623D149.jpg",
  ["9C142680869F83D21DFCDBAE7DB597DC77872E8E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/9C142680869F83D21DFCDBAE7DB597DC77872E8E.jpg",
  ["12A03AD807EF4D8E8DF26775217286EB9179E83E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/12A03AD807EF4D8E8DF26775217286EB9179E83E.jpg",
  ["18B80CF819FB46CC3B3F78732A421F273B5E4EFB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/18B80CF819FB46CC3B3F78732A421F273B5E4EFB.jpg",
  ["19A7DD0F688D265D14E42F70A6CC8B9EBBEEF5AD"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/19A7DD0F688D265D14E42F70A6CC8B9EBBEEF5AD.jpg",
  ["23FF6F08CEFFB5D8DABBA6F9E3C66B756E8DE254"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/23FF6F08CEFFB5D8DABBA6F9E3C66B756E8DE254.jpg",
  ["26B8ECBE5996B0555A9104F19050205DC31EBAA0"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/26B8ECBE5996B0555A9104F19050205DC31EBAA0.jpg",
  ["26FC1B238FF70E9873F071FFA380BD2214B9BD30"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/26FC1B238FF70E9873F071FFA380BD2214B9BD30.jpg",
  ["029D44A9185DA72DAD591DF7B732963D3509A04F"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/029D44A9185DA72DAD591DF7B732963D3509A04F.jpg",
  ["29E496E6E180EA77EA9078A7C50B1009DF25E3C8"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/29E496E6E180EA77EA9078A7C50B1009DF25E3C8.jpg",
  ["44E79BCCF2A4096D4EF6DF719CDDCD2A104172CE"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/44E79BCCF2A4096D4EF6DF719CDDCD2A104172CE.jpg",
  ["51B96BF4C4D7255F9E952AFA2AFF21BEE134B859"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/51B96BF4C4D7255F9E952AFA2AFF21BEE134B859.jpg",
  ["52B6740B6B1F229CBC4F745F00CED4E8AF28F3D7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/52B6740B6B1F229CBC4F745F00CED4E8AF28F3D7.jpg",
  ["65D0F3C7A50426841944C09864FB50F4C3658820"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/65D0F3C7A50426841944C09864FB50F4C3658820.jpg",
  ["70A4A02FF6E31FA586D025650C89FFF9B1684954"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/70A4A02FF6E31FA586D025650C89FFF9B1684954.jpg",
  ["72BD4DA812A98A54A994609240B1A97F81803EBA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/72BD4DA812A98A54A994609240B1A97F81803EBA.jpg",
  ["73CC276D13B6F29DB3D3177B840825B52F099EB6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/73CC276D13B6F29DB3D3177B840825B52F099EB6.jpg",
  ["80C2CB12E8FB3440D524322AF77D74D3DF818794"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/80C2CB12E8FB3440D524322AF77D74D3DF818794.jpg",
  ["84E87F411B934F95BF0B8C0567659A838C30B375"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/84E87F411B934F95BF0B8C0567659A838C30B375.jpg",
  ["88B0A6C057D6929A2C6873CA35B00D5D92575AC1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/88B0A6C057D6929A2C6873CA35B00D5D92575AC1.jpg",
  ["96A956FE09C62D9C60B980C0658B212B49AB2BAC"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/96A956FE09C62D9C60B980C0658B212B49AB2BAC.jpg",
  ["117B8CF5948E7AE036CF6E5766F2F8DEEA6A85AD"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/117B8CF5948E7AE036CF6E5766F2F8DEEA6A85AD.jpg",
  ["233D7D3353291C394E12BD0BF6857578D46AB806"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/233D7D3353291C394E12BD0BF6857578D46AB806.jpg",
  ["264BA26055EF157F9EF7B10E10F18E0F02E43442"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/264BA26055EF157F9EF7B10E10F18E0F02E43442.jpg",
  ["434F163F1A6C246B0394B10A5D18249CA62FD6BC"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/434F163F1A6C246B0394B10A5D18249CA62FD6BC.jpg",
  ["463CBBDE68516A4313DD97011C446C4966A75D4D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/463CBBDE68516A4313DD97011C446C4966A75D4D.jpg",
  ["476D910CDC5CB65CB62CBB8710A57E9665F9D97C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/476D910CDC5CB65CB62CBB8710A57E9665F9D97C.jpg",
  ["576C2D9285BEFF14F8C3F8814152C58EDB8A3508"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/576C2D9285BEFF14F8C3F8814152C58EDB8A3508.jpg",
  ["643F2E60A7C7418D3428605FA9C5EB32A7AD76C4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/643F2E60A7C7418D3428605FA9C5EB32A7AD76C4.jpg",
  ["0660FD0070CB68EA4638EC90B29A3B0446280FCA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0660FD0070CB68EA4638EC90B29A3B0446280FCA.jpg",
  ["662ADB367B2ED61BF04CA2D3A660C6C575A52C15"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/662ADB367B2ED61BF04CA2D3A660C6C575A52C15.jpg",
  ["698CD67753F14C9524D1F4897FCB15C5DCBAF1E8"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/698CD67753F14C9524D1F4897FCB15C5DCBAF1E8.jpg",
  ["717D3ADD1085CC91D10E22ACB8F67FCA8CDD0664"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/717D3ADD1085CC91D10E22ACB8F67FCA8CDD0664.jpg",
  ["876BE653C39BF957F014CBD2FB015A4C52F580AF"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/876BE653C39BF957F014CBD2FB015A4C52F580AF.jpg",
  ["890E7D0529A20884B47D45701CCC3ECA8BB00915"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/890E7D0529A20884B47D45701CCC3ECA8BB00915.jpg",
  ["971F716092AF560B33C538A98302C4F1BC94DD56"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/971F716092AF560B33C538A98302C4F1BC94DD56.jpg",
  ["1051AAAD026FB74714938F72A6CFFB3EEA360404"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1051AAAD026FB74714938F72A6CFFB3EEA360404.jpg",
  ["1159C01948CC55DE2BF2CC21294E09C1AFE28B9A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1159C01948CC55DE2BF2CC21294E09C1AFE28B9A.jpg",
  ["1561E32FBA1DD696CB34E5D8C0FF8CA8390166FA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1561E32FBA1DD696CB34E5D8C0FF8CA8390166FA.jpg",
  ["1973B557F97A7562D1CFE470195B07017B484906"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1973B557F97A7562D1CFE470195B07017B484906.jpg",
  ["2589DAB84B477016B7BB0BB2564A012D59D7823C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/2589DAB84B477016B7BB0BB2564A012D59D7823C.jpg",
  ["3161C9B31E75E588D72D7917DF31D5A654583CF5"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3161C9B31E75E588D72D7917DF31D5A654583CF5.jpg",
  ["3634E1AC531C63EC9AFA6A287C3E8649267EA50A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3634E1AC531C63EC9AFA6A287C3E8649267EA50A.jpg",
  ["4751A73625757AD88E14E22E4BCB5C9ADE853AC7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4751A73625757AD88E14E22E4BCB5C9ADE853AC7.jpg",
  ["5146E9968620FA16791C3087ACA39DA2EF78A865"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/5146E9968620FA16791C3087ACA39DA2EF78A865.jpg",
  ["6336F2FFF022784F5AE03A581C336EEC98E0E841"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6336F2FFF022784F5AE03A581C336EEC98E0E841.jpg",
  ["7422FDE2FCBA58E4E7EA890DAE306EF646830FA4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7422FDE2FCBA58E4E7EA890DAE306EF646830FA4.jpg",
  ["9294A5B4036205285A25C6854E4E7F61D29A8E9C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/9294A5B4036205285A25C6854E4E7F61D29A8E9C.jpg",
  ["9689FAE8A2604EE6E047D346197955006D84E3B6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/9689FAE8A2604EE6E047D346197955006D84E3B6.jpg",
  ["23527F7F5CDB4E2CE100DBE840C14F01F327DB0B"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/23527F7F5CDB4E2CE100DBE840C14F01F327DB0B.jpg",
  ["37002CD1CC0BE96CEEF3337FBD15B26A562CDB88"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/37002CD1CC0BE96CEEF3337FBD15B26A562CDB88.jpg",
  ["38770E5925913FE31788EE292A25C11721FDAEE8"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/38770E5925913FE31788EE292A25C11721FDAEE8.jpg",
  ["46873C9BA8A184E994D5F59FCFFD1FC8F49775C2"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/46873C9BA8A184E994D5F59FCFFD1FC8F49775C2.jpg",
  ["69792CBA07CF6FC4CCD39E4E8BB13C86D96EA141"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/69792CBA07CF6FC4CCD39E4E8BB13C86D96EA141.jpg",
  ["85931BD821142FE79EC7E4425D65C5D59537D543"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/85931BD821142FE79EC7E4425D65C5D59537D543.jpg",
  ["94239B7BE330476F52116EB4EC9A18AD0CE3D9DF"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/94239B7BE330476F52116EB4EC9A18AD0CE3D9DF.jpg",
  ["094675F88F200BFC77DA389E13B686560C6285C8"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/094675F88F200BFC77DA389E13B686560C6285C8.jpg",
  ["101562FA543E79B0A7D1470E336591D5843EE0ED"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/101562FA543E79B0A7D1470E336591D5843EE0ED.jpg",
  ["199461FA716EADF5BB28C428AB6089C1D6DC1097"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/199461FA716EADF5BB28C428AB6089C1D6DC1097.jpg",
  ["775875B4F19564B442D279C297C754587853C00D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/775875B4F19564B442D279C297C754587853C00D.jpg",
  ["6596852B75D2813CDFF5D9CB1DED5D80BDD5DA2A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6596852B75D2813CDFF5D9CB1DED5D80BDD5DA2A.jpg",
  ["7182737F66EA85481297C99B2537C8BB6072B218"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7182737F66EA85481297C99B2537C8BB6072B218.jpg",
  ["45245662CC12184895865B285C02B8BA52BF5D77"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/45245662CC12184895865B285C02B8BA52BF5D77.jpg",
  ["0600484406F9B7AB711A7CCEF40793B9A4A7A4E9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0600484406F9B7AB711A7CCEF40793B9A4A7A4E9.jpg",
  ["A8FC2D3519D65A04129AC8B8E0503371CAC9C887"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A8FC2D3519D65A04129AC8B8E0503371CAC9C887.jpg",
  ["A28EB8CCBA3C5899F73AA52B1A728C8420D05749"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A28EB8CCBA3C5899F73AA52B1A728C8420D05749.jpg",
  ["A7105E7EDD2AD203DD06E0E773BCECA472A79929"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A7105E7EDD2AD203DD06E0E773BCECA472A79929.jpg",
  ["A30849B3631C9B4CD63FB552CBD13E036A2FEA97"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A30849B3631C9B4CD63FB552CBD13E036A2FEA97.jpg",
  ["A6992685A7C00BC714C761B8837B931D646E2951"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A6992685A7C00BC714C761B8837B931D646E2951.jpg",
  ["AAF3F2653FAF2325A20273B6B9376B8D2BB9C72D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/AAF3F2653FAF2325A20273B6B9376B8D2BB9C72D.jpg",
  ["AC94CCF946FD4B484327BAF40153B08CA6595E7D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/AC94CCF946FD4B484327BAF40153B08CA6595E7D.jpg",
  ["AF34FFBF1C86D0CB2E50C1636FFC72D15EAD46FA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/AF34FFBF1C86D0CB2E50C1636FFC72D15EAD46FA.jpg",
  ["B3E6626A743696C75B9B80FF3BA867D3C684B146"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B3E6626A743696C75B9B80FF3BA867D3C684B146.jpg",
  ["B5F8D0BCAC0EC76D101D575C83B3452F75AE49A2"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B5F8D0BCAC0EC76D101D575C83B3452F75AE49A2.jpg",
  ["B7F5D9C472E31D6891D1D9CA7EF5062CC298E142"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B7F5D9C472E31D6891D1D9CA7EF5062CC298E142.jpg",
  ["B36E2F0A55D3C8A6C21523918A1C788544E26BA6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B36E2F0A55D3C8A6C21523918A1C788544E26BA6.jpg",
  ["B51BBEAD1634F573784C6801241D6D30880918E3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B51BBEAD1634F573784C6801241D6D30880918E3.jpg",
  ["B71A9ABF7E171B7AB2C134D6A46A170635012CA1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B71A9ABF7E171B7AB2C134D6A46A170635012CA1.jpg",
  ["B83CE41FF1FD70E4BE806AAE5673E683AF99D338"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B83CE41FF1FD70E4BE806AAE5673E683AF99D338.jpg",
  ["B85AE470D96B7CA85C4677B62C64B7A8251518DB"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B85AE470D96B7CA85C4677B62C64B7A8251518DB.jpg",
  ["B85C3E8F95A87363E4631D29B7BB1FD768676D60"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B85C3E8F95A87363E4631D29B7BB1FD768676D60.jpg",
  ["B86CC9D6411CC0448164FBD9A8F28A00990DC95A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B86CC9D6411CC0448164FBD9A8F28A00990DC95A.jpg",
  ["B94B60F9DC4B08F075C4F49DB5D574E993D85381"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B94B60F9DC4B08F075C4F49DB5D574E993D85381.jpg",
  ["B891CD1D5F2A5788066428CF262A92CDC1DE7F67"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/B891CD1D5F2A5788066428CF262A92CDC1DE7F67.jpg",
  ["BA51C3921EBE0D85C8ECB5535D8FA6F097BCD89C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/BA51C3921EBE0D85C8ECB5535D8FA6F097BCD89C.jpg",
  ["BDF7A52AF927137F7556F0980F482F62E6772703"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/BDF7A52AF927137F7556F0980F482F62E6772703.jpg",
  ["BDF1541873D367D9CE47C8F6824FC21DEC1FA932"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/BDF1541873D367D9CE47C8F6824FC21DEC1FA932.jpg",
  ["BE603DFA07315BD928292DBBB9DD2420D855A8AA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/BE603DFA07315BD928292DBBB9DD2420D855A8AA.jpg",
  ["BEA09DEA9C284C449015D4AE70F1EFACF5399F16"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/BEA09DEA9C284C449015D4AE70F1EFACF5399F16.jpg",
  ["C1C18822EF930E2D9CC3BA8CDA9E93AC6D13C75E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C1C18822EF930E2D9CC3BA8CDA9E93AC6D13C75E.jpg",
  ["C5D621F0D077C7FECDF1A5FDE811F56D17F4A598"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C5D621F0D077C7FECDF1A5FDE811F56D17F4A598.jpg",
  ["C10FDF6895D5BB820E952240863466AE746A2992"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C10FDF6895D5BB820E952240863466AE746A2992.jpg",
  ["C27C961AD07C7E59DC2E35A38110E140BBD492D3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C27C961AD07C7E59DC2E35A38110E140BBD492D3.jpg",
  ["C751CB80143F7BA01269775F220430755D26CB6D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C751CB80143F7BA01269775F220430755D26CB6D.jpg",
  ["C8447DB2F657CAF2BD02863869D659DD0116D0BD"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C8447DB2F657CAF2BD02863869D659DD0116D0BD.jpg",
  ["CA80FF9EF53599FD3F3B3D92959EA307F9E37A75"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CA80FF9EF53599FD3F3B3D92959EA307F9E37A75.jpg",
  ["CB1FABE3ED6F273E3EA0AC3CC95C4E36B59869A0"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CB1FABE3ED6F273E3EA0AC3CC95C4E36B59869A0.jpg",
  ["CB5AC17E66C95FC6FE64A8CB81E7A01709C23F01"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CB5AC17E66C95FC6FE64A8CB81E7A01709C23F01.jpg",
  ["CCA2BD7A6C21CDE7CC7C2BB661B8B7E7DA82AF52"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CCA2BD7A6C21CDE7CC7C2BB661B8B7E7DA82AF52.jpg",
  ["CD9156C58668567D8CD8A1802D2956238D38A8E7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CD9156C58668567D8CD8A1802D2956238D38A8E7.jpg",
  ["CE589BCFDE3D7979F3463107BC592AED1953659C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CE589BCFDE3D7979F3463107BC592AED1953659C.jpg",
  ["CEB365A8DE70FD12F5F17FBBFA4CA23DDE4927FD"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CEB365A8DE70FD12F5F17FBBFA4CA23DDE4927FD.jpg",
  ["CFB8CB5B5AD76F13AEC5A98A49C2B8B4E61E1CD9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CFB8CB5B5AD76F13AEC5A98A49C2B8B4E61E1CD9.jpg",
  ["D3EFA2CAE21CFC5C3B835CAAE026BF90436952D9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/D3EFA2CAE21CFC5C3B835CAAE026BF90436952D9.jpg",
  ["D25CB8B9273A52E564C002A66B5D8597A4DC6321"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/D25CB8B9273A52E564C002A66B5D8597A4DC6321.jpg",
  ["D295C9DCB56644EFB91917807ADF736F01F46CB3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/D295C9DCB56644EFB91917807ADF736F01F46CB3.jpg",
  ["D854AD818B0A64CA0CA4A1A05B11EA80699AC856"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/D854AD818B0A64CA0CA4A1A05B11EA80699AC856.jpg",
  ["D47746E7F6E12406D32BA20D85B126D0C050685E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/D47746E7F6E12406D32BA20D85B126D0C050685E.jpg",
  ["D59635EE6A48B7EAE6F8D747407BA71B688C5CE1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/D59635EE6A48B7EAE6F8D747407BA71B688C5CE1.jpg",
  ["DA3517DD1264939CDAB36A2896BD313D2CDBF9FE"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DA3517DD1264939CDAB36A2896BD313D2CDBF9FE.jpg",
  ["DAA6B3F6C9F6F88212B73C160F9B0EEB51064BF6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DAA6B3F6C9F6F88212B73C160F9B0EEB51064BF6.jpg",
  ["DACD5621CA7BF6EBB75CCB8284F667292316E404"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DACD5621CA7BF6EBB75CCB8284F667292316E404.jpg",
  ["DBA3D3AB1C3634B55D198B167CCDDC198BCB9519"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DBA3D3AB1C3634B55D198B167CCDDC198BCB9519.jpg",
  ["DE164F5970869F79C41A3D7AC2275DFAF6B66A60"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DE164F5970869F79C41A3D7AC2275DFAF6B66A60.jpg",
  ["DF21C3DBB8F3663063224BBBACCB469D4CEEFD09"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DF21C3DBB8F3663063224BBBACCB469D4CEEFD09.jpg",
  ["DFC2A8A4F29BA8D2C08D1C407BE8694E298B3723"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DFC2A8A4F29BA8D2C08D1C407BE8694E298B3723.jpg",
  ["E7D7BBF54BB94027B16A3F6CD4DEF0B480EF47E1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E7D7BBF54BB94027B16A3F6CD4DEF0B480EF47E1.jpg",
  ["E99A958BE6477E1AD3B46BE21C147BDC602EA78F"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E99A958BE6477E1AD3B46BE21C147BDC602EA78F.jpg",
  ["E23255CE07BC281DB0FE9DA22609A9D07AC2F252"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E23255CE07BC281DB0FE9DA22609A9D07AC2F252.jpg",
  ["EBB69999BD4AED953279C494BD527A808E8DA5E3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/EBB69999BD4AED953279C494BD527A808E8DA5E3.jpg",
  ["EDBEAA0AEB59E9C2D7AB6992A417DEA1C502B985"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/EDBEAA0AEB59E9C2D7AB6992A417DEA1C502B985.jpg",
  ["EE9B8D634C18C2035E131430B9B78EE8F30FA6AA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/EE9B8D634C18C2035E131430B9B78EE8F30FA6AA.jpg",
  ["EF894027EF46A36A2A95292F6AA620D7CCA77F97"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/EF894027EF46A36A2A95292F6AA620D7CCA77F97.jpg",
  ["EFE45D226E1DF1FCE94924E1E2E30C4A923D525F"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/EFE45D226E1DF1FCE94924E1E2E30C4A923D525F.jpg",
  ["F2FB3187FE8327385C7593120E8CBA0C5B784BBD"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F2FB3187FE8327385C7593120E8CBA0C5B784BBD.jpg",
  ["F5BB16F291DD890DE755F6CC4A6DBAFDD14EE0F6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F5BB16F291DD890DE755F6CC4A6DBAFDD14EE0F6.jpg",
  ["F5BEF5572A384085BBF435B70DEB6850DF64DC9D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F5BEF5572A384085BBF435B70DEB6850DF64DC9D.jpg",
  ["F6CA0AEDB949094AA32E74243CEBCA299FA31B76"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F6CA0AEDB949094AA32E74243CEBCA299FA31B76.jpg",
  ["F7F12E3B62C96592D061F3CE2C470857837FC145"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F7F12E3B62C96592D061F3CE2C470857837FC145.jpg",
  ["F24DA9DDC660F2B8746381DC87BEFA28ECC19B9F"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F24DA9DDC660F2B8746381DC87BEFA28ECC19B9F.jpg",
  ["F43FE9E622FFCCFA971BC2084BEA4DDD3CDBE633"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F43FE9E622FFCCFA971BC2084BEA4DDD3CDBE633.jpg",
  ["F74DAC176BF7CFD97976A7AC085887C03934D3F6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F74DAC176BF7CFD97976A7AC085887C03934D3F6.jpg",
  ["F76C3B973AD6A51D7D1CE83F2FD332161EE1DC19"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F76C3B973AD6A51D7D1CE83F2FD332161EE1DC19.jpg",
  ["F732EDEA89346E28FBD7C5E186BDE1921C02E259"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F732EDEA89346E28FBD7C5E186BDE1921C02E259.jpg",
  ["F5456AF1770C2447F790F108851376C4A67A55B7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F5456AF1770C2447F790F108851376C4A67A55B7.jpg",
  ["F4591393E95898268542974DE06A8CC6A5E72899"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F4591393E95898268542974DE06A8CC6A5E72899.jpg",
  ["F79373804CB2A3FBD821E6C4E71097FF3BE94FE7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F79373804CB2A3FBD821E6C4E71097FF3BE94FE7.jpg",
  ["FD02F4F271FF12693A292A9C096B679F7D222CD6"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/FD02F4F271FF12693A292A9C096B679F7D222CD6.jpg",
  ["FE2D84E8BD01C333944CE645789646AA14DBE2D4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/FE2D84E8BD01C333944CE645789646AA14DBE2D4.jpg",
  ["FF6A12E3ABC0D1259291BF6CE7395795C125ABF9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/FF6A12E3ABC0D1259291BF6CE7395795C125ABF9.jpg",
  ["27D995A763BB0FB7160220F2BF24B659A2246247"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/27D995A763BB0FB7160220F2BF24B659A2246247.png",
  ["0CDBB21FC76E008B0296B941BDB5F581E1311B20"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/0CDBB21FC76E008B0296B941BDB5F581E1311B20.png",
  ["01CD25F0A759C1F87B1E00ED31EB372832472564"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/01CD25F0A759C1F87B1E00ED31EB372832472564.png",
  ["02F20CD62D677774E4278F1DEC7EA9EC6B4FC732"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/02F20CD62D677774E4278F1DEC7EA9EC6B4FC732.png",
  ["3A7B7FB4612CF7DD9D4DEB8C2F10798060BA31B4"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/3A7B7FB4612CF7DD9D4DEB8C2F10798060BA31B4.png",
  ["04A66194395CE0AA10BF466B25498058B4F0C319"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/04A66194395CE0AA10BF466B25498058B4F0C319.png",
  ["4C4F0849A6FCA39BE9854684409390F2465519D3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/4C4F0849A6FCA39BE9854684409390F2465519D3.png",
  ["6DBD1ABDBE59DBEE85F4BD96C1A900E409BCED5C"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/6DBD1ABDBE59DBEE85F4BD96C1A900E409BCED5C.png",
  ["7D58D4455C32C3D0A3EDE104807E8A60C7F3C027"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/7D58D4455C32C3D0A3EDE104807E8A60C7F3C027.png",
  ["11B413389741A024D5442D49857356FDEA2E9B1D"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/11B413389741A024D5442D49857356FDEA2E9B1D.png",
  ["27E3890FA9831A3554F23EFAEC0F6291FB5F2CD3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/27E3890FA9831A3554F23EFAEC0F6291FB5F2CD3.png",
  ["48CB21C8E019D54089957AAC4B509CEFDB1638DC"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/48CB21C8E019D54089957AAC4B509CEFDB1638DC.png",
  ["49B7CC620763EB1AE4DBE069D5F773C442EAC935"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/49B7CC620763EB1AE4DBE069D5F773C442EAC935.png",
  ["076F530391D802B4706F1F467CC5BCFB156BAD6A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/076F530391D802B4706F1F467CC5BCFB156BAD6A.png",
  ["99DD8228ACB2BD78952C630F68A169620A263BA3"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/99DD8228ACB2BD78952C630F68A169620A263BA3.png",
  ["248FF6236143E580D1012226A6C75B2C8A24CD95"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/248FF6236143E580D1012226A6C75B2C8A24CD95.png",
  ["707BF44BA25001B4F39F2DCB746D44240AE693B7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/707BF44BA25001B4F39F2DCB746D44240AE693B7.png",
  ["862C274D346DDD3DB57BAF0199E8B42CFE8F97F7"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/862C274D346DDD3DB57BAF0199E8B42CFE8F97F7.png",
  ["1650C692E6A966C90F70F0DD9D712D0997FB720B"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/1650C692E6A966C90F70F0DD9D712D0997FB720B.png",
  ["2486A61E5D058809599A914A9D57FFAD8AE1BFD9"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/2486A61E5D058809599A914A9D57FFAD8AE1BFD9.png",
  ["844108A713472993695426D65F860475EE6A34DE"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/844108A713472993695426D65F860475EE6A34DE.png",
  ["736371115C5768977BE9EF8B4D6FCC8AE40AF022"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/736371115C5768977BE9EF8B4D6FCC8AE40AF022.png",
  ["A81E84E55066E73E167A739D838C2CB378A4384B"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A81E84E55066E73E167A739D838C2CB378A4384B.png",
  ["A347FD958D38483F56DDA65635AECCF1DEB4AA07"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/A347FD958D38483F56DDA65635AECCF1DEB4AA07.png",
  ["AFAFF3558C7AA0B59A7A83ED83A40B322A9F323E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/AFAFF3558C7AA0B59A7A83ED83A40B322A9F323E.png",
  ["C0CE4AB850B2FB4AAAD6E231D84ED7F47A737155"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C0CE4AB850B2FB4AAAD6E231D84ED7F47A737155.png",
  ["C8EF71862BF920A1B22005C9E67DE92AC4BE52DA"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C8EF71862BF920A1B22005C9E67DE92AC4BE52DA.png",
  ["C436BCC6FCCBB82B2E5BC9446D73AA778E41A127"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/C436BCC6FCCBB82B2E5BC9446D73AA778E41A127.png",
  ["CBABA30749A450D86634BDD8E4711FB47E9AA97A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/CBABA30749A450D86634BDD8E4711FB47E9AA97A.png",
  ["E3FACA6D0AE9ECD0DBF6502013695AEDF4C6485E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E3FACA6D0AE9ECD0DBF6502013695AEDF4C6485E.png",
  ["E7E980C75C3D232C2F6EECFB8751C9353BC5F0BC"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E7E980C75C3D232C2F6EECFB8751C9353BC5F0BC.png",
  ["E8C0E6DF5E12FB506ECF35BB6D71DC33947FF2B1"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E8C0E6DF5E12FB506ECF35BB6D71DC33947FF2B1.png",
  ["E471C23EF7590ABFE1EAA477FD5700F282AD0922"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/E471C23EF7590ABFE1EAA477FD5700F282AD0922.png",
  ["ED39AF679E787381E1B6F28E2D3EE7C2AF2BA115"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/ED39AF679E787381E1B6F28E2D3EE7C2AF2BA115.png",
  ["F05E55A70DF094C83C7A242FEDF700930DBC393E"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F05E55A70DF094C83C7A242FEDF700930DBC393E.png",
  ["F6A5837D83896E8C5C9B6A7494E01D0C2FE60A87"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F6A5837D83896E8C5C9B6A7494E01D0C2FE60A87.png",
  ["F0829C22593A3DC8BF5D1899714BCB2C195F5D1F"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/F0829C22593A3DC8BF5D1899714BCB2C195F5D1F.png",
  ["FFEC3013B01A62A7CB747C5157F8C0CF1584CD9A"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/FFEC3013B01A62A7CB747C5157F8C0CF1584CD9A.png",
  ["32A8C1100EFC27A047E2F18E7617203D51C2BB85"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/32A8C1100EFC27A047E2F18E7617203D51C2BB85.jpg",
  ["DDF4A08A29D281BEF20D4380DC62FC6043083A03"] = "http://raw.githubusercontent.com/Eunomiac/VtmHforTTS/master/kingsdilemma/assets/Bulk/DDF4A08A29D281BEF20D4380DC62FC6043083A03.jpg"
}


C.SeatAngleSpan = 220

C.TableRadius = 57

C.TableHeight = 1.46 -- toCheck: lua log(tbl.getBounds().center:add(tbl.getBounds().offset):add(tbl.getBounds().size))
C.BoardHeight = 1.92

C.BaseHandTransform = {
	position = Vector(0, 3, C.TableRadius),
	rotation = Vector(0, 180, 0),
	scale = Vector(12, 5, 4)
}

C.AdminID = "76561198002132577"

C.SeatColors = {"Brown", "Red", "Orange", "Yellow", "Green"}

C.Houses = {"Allwed", "Blodyn", "Coden", "Crann", "Dualak", "Gamam", "Natar", "Olwyn", "Solad", "Tiryll", "Tork", "Wylio"}

C.Resources = {"Influence", "Wealth", "Morale", "Welfare", "Knowledge"}
C.Modes = {
	NONE = "NONE",
	SESSIONINIT = "SESSIONINIT",
	CHRONSETUP = "CHRONSETUP",
	GAMESETUP = "GAMESETUP",
	PLAY = "PLAY",
	END = "END"
}

C.Phases = {
	NONE = "NONE",
	SESSIONINIT = {
		SeatPlayers = "SeatPlayers",
		HouseSelection = "HouseSelection"
	},
	CHRONSETUP = "CHRONSETUP",
	GAMESETUP = {
		MainBoard = "MainBoard",
		LeaderModerator = "LeaderModerator",
		LegacySetup = "LegacySetup",
		SecretAgendas = "SecretAgendas",
		PrepareFirstRound = "PrepareFirstRound"
	},
	PLAY = {
		StartRound = "StartRound",
		DrawDilemma = "DrawDilemma",
		Discussion = "Discussion",
		Vote = "Vote",
		VoteResolution = "VoteResolution",
		DilemmaResolution = "DilemmaResolution"
	},
	END = {
		Score = "Score",
		Realm = "Realm",
		Achievements = "Achievements",
		Alignments = "Alignments",
		Cleanup = "Cleanup"
	}
}

C.RoundSteps = {
	Draw = "Draw",
	Vote = {
		ActivatePlayerVoteZones = {
			AyeZone = "active, oppToNay",
			NayZone = "active, oppToAye",
			PublicZone = "inactive",
			PassCard = "canPassAndMod" and "active, flippable" or "active, locked"
		},
		ActivateVotingLightModes = {

		},
		Leader_StartTurn = "SetLightModes",
			-- Wait for Leader to Pass Turn
		EndTurn = {
			DeterminePlayerVoteStatus = {
				[false] = {
					AyeOrNay = {
						"MovePowerToPublicPlinth",
						"UpdateOverallTotalDisplay",
						"RaisePlayerPlithsProportionally"
					},
					Pass = {
						"DeactivateLights",
						"SetZones"
					}
				},
				AyeOrNay = {
					"MovePowerToPublicPlinth",
					"UpdateOverallTotalDisplay",
					"RaisePlayerPlithsProportionally"
				}, -- because "stay" is really just 'move zero power'
				-- no 'Pass' because a passed player is out of voting.
			},
			CleanUp = {
				"CheckForLeaderTransfer",
				"CheckForNextTurn_OR_DIR.ADVANCE",
				"TransferTurn-LoopBack"
			}
		}
	},
	VoteResolution = {
		"DetermineWinner", -- with possible Moderator tiebreaker
		"ReassignLeader",
		"DistributePassCardCoin",
		"DistributeBalancePower",
		"WinningPowerToBalance",
		"RecoverLosingPower",
		"ResetVotingState"
	},
	DilemmaResolution = {
		"DisplayOutcome", -- players manually adjust board tokens here
		"ApplyMomentum",
		"ChronicleSticker",
		"StageEnvelope",
		"PlaceDilemmaCard",
		"OpenStagedEnvelope",
		"CheckKingStatus",
		"EndRound"
	}
}

C.CameraAngles = {
	BehindScreen = {
		isPlayerAngle = true,
		position = Vector({0,-14.25,1.5}),
		pitch = 30.7,
		yaw = 180,
		distance = 75
	},
	Lectern = {
		position = Vector({0,-6.25,74}),
		pitch = 12.67,
		yaw = 0,
		distance = 75
	},
	DilemmaPlinth = {
		position = Vector({0,-6.2,58.25}),
		pitch = 14.34,
		yaw = 0,
		distance = 75
	},
	DilemmaDraw = {
		position = Vector({0,13.11,50.15}),
		pitch = 1.51,
		yaw = 0,
		distance = 75
	},
	MainBoard = {
		position = Vector({0,-14.25,27.7}),
		pitch = 30.67,
		yaw = 0,
		distance = 75
	}
}

C.Spots = {
	Storage = {
		HouseCard = {
			position = Vector({104.00, 29.25, -2.25}),
			rotation = Vector({71.10, 180.00, 180.00}),
			scale = Vector({0.30, 1.00, 0.30})
		},
		Envelopes = {
			position = Vector({3.67, 7.25, 48.00}),
			rotation = Vector({320.42, 0.00, 0.00}),
			scale = Vector({0.19, 0.07, 0.10})
		},
		Stickers = {
			position = Vector({-3.67, 7.25, 48.00}),
			rotation = Vector({320.42, 0.00, 0.00}),
			scale = Vector({0.19, 0.07, 0.10})
		},
		MysteryEnvelopes = {
			position = Vector({0.00, 8.05, 50.27}),
			rotation = Vector({0.00, 90.00, 320.42}),
			scale = Vector({1.15, 0.23, 6.30})
		},
		LeaderLight = {
			position = Vector({-7.78, 15.62, 35.10}),
			rotation = Vector({0, 180, 0}),
			scale = Vector({1, 1, 1})
		},
		LeaderFigure = {
			position = Vector({-7.78, 5.51, 35.08}),
			rotation = Vector({359.77, 359.86, 0.05}),
			scale = Vector({1, 1, 1})
		},
		ModeratorLight = {
			position = Vector({7.78, 15.68, 35.10}),
			rotation = Vector({0, 180, 0}),
			scale = Vector({1, 1, 1})
		},
		ModeratorFigure = {
			position = Vector({7.78, 1.39, 35.10}),
			rotation = Vector({0.00, 219.63, 0.00}),
			scale = Vector({0.3, 0.3, 0.3})
		},
		SecretAgenda = {
			position = Vector({0.00, 1.50, 33.79}),
			rotation = Vector({0, 270, 180})
		}
	},
	Staging = {
		Lectern = {
			Envelopes = {
				position = Vector({0.00, 12.00, 45.50}),
				rotation = Vector({285.00, 0.00, 0.00}),
				scale = Vector({0.19, 0.07, 0.10})
			},
			Stickers = {
				position = Vector({0.00, 12.00, 45.50}),
				rotation = Vector({285.00, 0.00, 0.00}),
				scale = Vector({0.19, 0.07, 0.10})
			},
			MysteryEnvelopes = {
				position = Vector({0.00, 15.03, 50.28}),
				rotation = Vector({0.00, 90.00, 270.00}),
				scale = Vector({1.15, 0.23, 6.30})
			},
			Display = {
				position = Vector({0.00, 12.00, 42.00}),
				rotation = Vector({62.95, 179.98, 0.00}),
				scale = Vector({1.59, 1.00, 1.59})
			},
			TopCard = {
				position = Vector({0.00, 13.22, 40.62}),
				rotation = Vector({62.95, 180.00, 0.00}),
				scale = Vector({1.59, 1.00, 1.59})
			},
			RestOfDeck = {
				position = Vector({0.00, 9.32, 41.94}),
				rotation = Vector({0.00, 90.00, 0.00}),
				scale = Vector({1.59, 1.00, 1.59})
			}
		},
		StoryCard = {
			Display = {
				position = Vector({0, 1.94, 16.52}),
				rotation = Vector({0, 180, 0}),
				scale = Vector({1.59, 1.00, 1.59})
			}
		},
		SecretAgenda = {
			High = {
				position = Vector({0.00, 15.00, 26.00}),
				rotation = Vector({0.00, 180, 180.00})
			},
			Low = {
				position = Vector({0.00, 5.37, 25.04}),
				rotation = Vector({18, 180, 180.00})
			},
			Burnt = {
				position = Vector({0.00, 2.27, 52.08}),
				rotation = Vector(90, 500, 500)
			}
		},
		DilemmaDraw = {
			position = Vector({0.00, 7.05, 24.61}),
			rotation = Vector({25.36, 180, 0})
		}
	},
	Main = {
		CoverCard = {
			Closed = {
				position = Vector({0.00, 6, 26.00}),
				rotation = Vector({0.00, 270, 0.00}),
				scale = Vector({2.55, 1.00, 2.57})
			},
			Open = {
				position = Vector({0.00, 6.67, 23}),
				rotation = Vector({0, 270, 290}),
				scale = Vector({2.55, 1.00, 2.57})
			}
		},
		ChronicleCard = {
			position = Vector({0.00, 3.93, 37.12}),
			rotation = Vector({78.09, 180.00, 0.00}),
			scale = Vector({2.60, 1.00, 2.60})
		},
		Dilemma = {
			deck = {
				position = Vector({0.00, 6, 26.00}),
				rotation = Vector({0.00, 90.00, 0.00}),
				scale = Vector({1.59, 1.00, 1.59})
			},
			aboveDeck = {
				position = Vector({0.00, 6, 26.00}),
				rotation = Vector({0.00, 180.00, 0.00}),
				scale = Vector({1.59, 1.00, 1.59})
			},
			faceDown = {
				position = Vector({0.00, 28.51, 43.94}),
				rotation = Vector(90, 180, 0),
				scale = Vector(10, 1, 10)
			},
			faceUpAye = {
				position = Vector({0, 0.81, 39.30}),
				rotation = Vector({90, 0, 0}),
				scale = Vector({10, 1.00, 10})
			},
			faceUpNay = {
				position = Vector({0.00, 1.57, 39.30}),
				rotation = Vector({270, 180, 0}),
				scale = Vector({10, 1.00, 10})
			},
			boardAye = {
				{
					position = Vector({-7.4, 4, 8.05}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, 3.63}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -0.80}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -5.23}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -9.65}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -14.08}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -14.08}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -18.50}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -18.74}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -18.99}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -19.23}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -19.47}),
					rotation = Vector({0, 90, 180}),
					scale = Vector({1.59, 1, 1.59})
				}
			},
			boardNay = {
				{
					position = Vector({-7.4, 4, 8.05}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, 3.63}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -0.80}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -5.23}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -9.65}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -14.08}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -14.08}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -18.50}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -18.74}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -18.99}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -19.23}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				},
				{
					position = Vector({-7.4, 4, -19.47}),
					rotation = Vector({0, 270, 180}),
					scale = Vector({1.59, 1, 1.59})
				}
			}
		}
	},
	Board = {
		StabilityToken = {
			top = {
				position = Vector({-4.83, C.BoardHeight, 9.43}),
				rotation = Vector({0, 180, 0}),
				scale = Vector({0.6, 1, 0.6})
			},
			center = {
				position = Vector({-4.83, C.BoardHeight, -3.35}),
				rotation = Vector({0, 180, 0}),
				scale = Vector({0.6, 1, 0.6})
			},
			bottom = {
				position = Vector({-4.83, C.BoardHeight, -15.91}),
				rotation = Vector({0, 180, 0}),
				scale = Vector({0.6, 1, 0.6})
			}
		},
		ResourceTokens = {
			Influence = {
				top = {
					position = Vector({-2.71, C.BoardHeight, 8.04}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				center = {
					position = Vector({-2.71, C.BoardHeight, -3.18}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				bottom = {
					position = Vector({-2.71, C.BoardHeight, -14.42}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				}
			},
			Wealth = {
				top = {
					position = Vector({-1.38, C.BoardHeight, 8.04}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				center = {
					position = Vector({-1.38, C.BoardHeight, -3.20}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				bottom = {
					position = Vector({-1.38, C.BoardHeight, -14.42}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				}
			},
			Morale = {
				top = {
					position = Vector({-0.02, C.BoardHeight, 8.04}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				center = {
					position = Vector({-0.02, C.BoardHeight, -3.22}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				bottom = {
					position = Vector({-0.02, C.BoardHeight, -14.42}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				}
			},
			Welfare = {
				top = {
					position = Vector({1.33, C.BoardHeight, 8.04}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				center = {
					position = Vector({1.33, C.BoardHeight, -3.20}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				bottom = {
					position = Vector({1.33, C.BoardHeight, -14.42}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				}
			},
			Knowledge = {
				top = {
					position = Vector({2.69, C.BoardHeight, 8.04}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				center = {
					position = Vector({2.69, C.BoardHeight, -3.18}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				},
				bottom = {
					position = Vector({2.69, C.BoardHeight, -14.42}),
					rotation = Vector({0, 180, 0}),
					scale = Vector({0.6, 1, 0.6})
				}
			}
		},
		ChronicleStickers = {
			top = {
				position = Vector({4, C.BoardHeight, 20.55}),
				rotation = Vector({0, 180, 0}),
				scale = Vector({1,1,1})
			},
			center = {
				position = Vector({4, C.BoardHeight, 16.05}),
				rotation = Vector({0, 180, 0}),
				scale = Vector({1,1,1})
			},
			bottom = {
				position = Vector({-4, C.BoardHeight, 11.55}),
				rotation = Vector({0, 180, 0}),
				scale = Vector({1,1,1})
			}
		},
		BalancePlinth = {
			up = {
				position = Vector({0, 3, -19.17}),
				rotation = Vector({0, 0, 0}),
				scale = Vector({0.33, 0.54, 0.33})
			},
			down = {
				position = Vector({0, 1.75, -19.17}),
				rotation = Vector(0, 0, 0)
			}
		}
	},
	Player = {
		Power = {
			position = Vector({8, 2, 48}),
			rotation = Vector({0, 0, 0})
		},
		Coin = {
			position = Vector({-8, 2, 48}),
			rotation = Vector({0, 250, 0})
		},
		SecretAgenda = {
			position = Vector({10.00, 7.00, 42.50}),
			rotation = Vector({87.76, 0.00, 45.00})
		}
	}
}



C.LightColors = {
	Ambient = Color(0.5, 0.5, 0.5),
	StabilityToken = {
		center = Color(1, 1, 1),
		half = Color(1, 0.8, 0.5),
		ends = Color(1, 0, 0)
	},
	Balance = Color(1, 0.9, 0.25),
	Amber = Color(1, 0.67, 0),
	Yellow = Color(1, 0.88, 0),
	Blue = Color(0, 1, 1),
	Red = Color(1, 0, 0)
}

C.rotFaceDown = {0, 0, 0}
C.rotFaceUp = {0, 180, 0}

C.scanData = {
	Blodyn = {
		globalOffsets = {gx = 0.002, gy = 0.02},
		textWidth = 3400,
		nameOffsets = {dx = -0.16, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.31, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 4, zFix = 0.45, zScale = 0.065},
				{num = 2, zFix = 0.94, zScale = 0.065},
				{num = 2, zFix = 1.25, zScale = 0.065}
			}
		}
	},
	Coden = {
		globalOffsets = {gx = 0, gy = 0},
		textWidth = 3400,
		nameOffsets = {dx = -0.16, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.31, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 2, zFix = 0.445, zScale = 0.065},
				{num = 3, zFix = 0.785, zScale = 0.065},
				{num = 2, zFix = 1.18, zScale = 0.065}
			}
		}
	},
	Gamam = {
		globalOffsets = {gx = 0, gy = 0.02},
		textWidth = 3400,
		nameOffsets = {dx = -0.16, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.3, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 2, zFix = 0.45, zScale = 0.065},
				{num = 3, zFix = 0.81, zScale = 0.065},
				{num = 3, zFix = 1.17, zScale = 0.065}
			}
		}
	},
	Natar = {
		globalOffsets = {gx = 0.004, gy = 0.01},
		textWidth = 3400,
		nameOffsets = {dx = -0.16, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.3, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 3, zFix = 0.43, zScale = 0.065},
				{num = 2, zFix = 0.84, zScale = 0.065},
				{num = 3, zFix = 1.1, zScale = 0.065}
			}
		}
	},
	Olwyn = {
		globalOffsets = {gx = 0.005, gy = 0},
		textWidth = 3400,
		nameOffsets = {dx = -0.16, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.3, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 2, zFix = 0.49, zScale = 0.065},
				{num = 2, zFix = 0.92, zScale = 0.065},
				{num = 3, zFix = 1.25, zScale = 0.065}
			}
		}
	},
	Solad = {
		globalOffsets = {gx = 0, gy = 0},
		textWidth = 3600,
		nameOffsets = {dx = -0.12, dy = -0.8},
		prestigeGap = 0.065,
		agendaGap = 0.79,
		achievementButtons = {
			offsets = {dx = 1.315, dy = -0.64, zStart = 0.14},
			blocks = {
				{num = 2, zFix = 0.44, zScale = 0.07},
				{num = 2, zFix = 0.79, zScale = 0.07},
				{num = 2, zFix = 1.12, zScale = 0.07}
			}
		}
	},
	Allwed = {
		globalOffsets = {gx = 0.001, gy = 0.01},
		textWidth = 3000,
		nameOffsets = {dx = -0.19, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.3, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 2, zFix = 0.45, zScale = 0.065},
				{num = 4, zFix = 0.86, zScale = 0.065},
				{num = 3, zFix = 1.33, zScale = 0.065}
			}
		}
	},
	Crann = {
		globalOffsets = {gx = 0.001, gy = 0.01},
		textWidth = 3000,
		nameOffsets = {dx = -0.19, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.305, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 2, zFix = 0.49, zScale = 0.065},
				{num = 2, zFix = 0.85, zScale = 0.065},
				{num = 3, zFix = 1.165, zScale = 0.065}
			}
		}
	},
	Dualak = {
		globalOffsets = {gx = 0.001, gy = 0.01},
		textWidth = 3000,
		nameOffsets = {dx = -0.19, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.302, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 3, zFix = 0.411, zScale = 0.065},
				{num = 2, zFix = 0.78, zScale = 0.065},
				{num = 2, zFix = 1.1, zScale = 0.065}
			}
		}
	},
	Tiryll = {
		globalOffsets = {gx = 0, gy = 0.01},
		textWidth = 3400,
		nameOffsets = {dx = -0.16, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.3, dy = -0.64, zStart = 0.14},
			blocks = {
				{num = 2, zFix = 0.46, zScale = 0.07},
				{num = 2, zFix = 0.83, zScale = 0.07},
				{num = 2, zFix = 1.15, zScale = 0.07}
			}
		}
	},
	Tork = {
		globalOffsets = {gx = 0.002, gy = 0},
		textWidth = 3400,
		nameOffsets = {dx = -0.16, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.3, dy = -0.64, zStart = 0.13},
			blocks = {
				{num = 2, zFix = 0.46, zScale = 0.065},
				{num = 2, zFix = 0.86, zScale = 0.065},
				{num = 3, zFix = 1.19, zScale = 0.065}
			}
		}
	},
	Wylio = {
		globalOffsets = {gx = 0, gy = 0.01},
		textWidth = 3200,
		nameOffsets = {dx = -0.18, dy = -0.8},
		prestigeGap = 0.062,
		agendaGap = 0.78,
		achievementButtons = {
			offsets = {dx = 1.305, dy = -0.64, zStart = 0.12},
			blocks = {
				{num = 3, zFix = 0.39, zScale = 0.065},
				{num = 2, zFix = 0.79, zScale = 0.07},
				{num = 3, zFix = 1.13, zScale = 0.065}
			}
		}
	}
}

C.Images = {
	Flags = {
		Base = {
			Allwed = "http://cloud-3.steamusercontent.com/ugc/2064377962739194792/C9B66702A87E6D1FDB5384B4F51A5D77D2634917/",
			Blodyn = "http://cloud-3.steamusercontent.com/ugc/2064377962739253245/C9DBFEEB59A7B71D0A27FF280334271818FB26A0/",
			Coden = "http://cloud-3.steamusercontent.com/ugc/2064377962739253338/EA28A27B464F7693CC133B4E2FE6015B8C5CF0E3/",
			Crann = "http://cloud-3.steamusercontent.com/ugc/2064377962739253435/EE7BDEC5F7E46AC930644FC7533079F6879F5433/",
			Dualak = "http://cloud-3.steamusercontent.com/ugc/2064377962739253510/A16DF1A670D95E1C866F918ACE227092DBE9352B/",
			Gamam = "http://cloud-3.steamusercontent.com/ugc/2064377962739253616/87E88E5AC38BDC76F98654E1C280AA0A6E510C4E/",
			Natar = "http://cloud-3.steamusercontent.com/ugc/2064377962739253752/97822A3B8F0A01116CE2B721BB52E25A4317C218/",
			Olwyn = "http://cloud-3.steamusercontent.com/ugc/2064377962739253853/BB38AE3D3F420C0FD61BF814FD7775D462016AC8/",
			Solad = "http://cloud-3.steamusercontent.com/ugc/2064377962739253975/092946C413889BB5FC5E0D3F65C4C5EE136396BE/",
			Tiryll = "http://cloud-3.steamusercontent.com/ugc/2064377962739254148/DAC3E6F35DA73048387F0A2DEA8432C802AF83E3/",
			Tork = "http://cloud-3.steamusercontent.com/ugc/2064377962739254244/C64C331492D2A1AE626A63DEDEEA15CA99F5AF7A/",
			Wylio = "http://cloud-3.steamusercontent.com/ugc/2064377962739254331/8FD06EFCCF997781E5823A58C8DC3C3776866DD5/"
		},
		Claimed = {
			Allwed = "http://cloud-3.steamusercontent.com/ugc/2064378834882481449/963A8B75C9B97BDFF3D39E9D2BA5A544938954E1/",
			Blodyn = "http://cloud-3.steamusercontent.com/ugc/2064378834882481603/9BE1EE4AEAA99E52AEA5EED6FD4A7036E16A4A17/",
			Coden = "http://cloud-3.steamusercontent.com/ugc/2064378834882481665/DA4FE160EBBB082B654F2092437D146CDDD345BE/",
			Crann = "http://cloud-3.steamusercontent.com/ugc/2064378834882481723/16D0A4A74E791F5B809BD9CBE163D82BBDD70411/",
			Dualak = "http://cloud-3.steamusercontent.com/ugc/2064378834882481782/135D0D733C7715712302D85A5934CDB4CA016C19/",
			Gamam = "http://cloud-3.steamusercontent.com/ugc/2064378834882481847/21F19D0E431C93E5BAA92BD55E171162C550DCAE/",
			Natar = "http://cloud-3.steamusercontent.com/ugc/2064378834882481904/BABC349974DA713FA78C507B6B87A239A758B140/",
			Olwyn = "http://cloud-3.steamusercontent.com/ugc/2064378834882481956/263331DCE7B4ADEE222632B4BDCFF69C0CBFF479/",
			Solad = "http://cloud-3.steamusercontent.com/ugc/2064378834882482018/DB4192485CD507073895CE07E0F82FD0BFB778FE/",
			Tiryll = "http://cloud-3.steamusercontent.com/ugc/2064378834882482078/1F0131767099772ED3A445CB829A625EA609045E/",
			Tork = "http://cloud-3.steamusercontent.com/ugc/2064378834882482152/FEFD89F47ED3313B7CDAD5DB233EA94C58A025D7/",
			Wylio = "http://cloud-3.steamusercontent.com/ugc/2064378834882482218/BA59D16ACA1FB4220686BDBB50BA10DF076D4C62/"
		},
		HoverText = {
			Allwed ="http://cloud-3.steamusercontent.com/ugc/2064377962739254406/9003D12A2F60763746F70FD85B030CB56926FA3E/",
			Blodyn ="http://cloud-3.steamusercontent.com/ugc/2064377962739254471/6AE191A3885504DDCD870F5C7468649C44CA96A1/",
			Coden ="http://cloud-3.steamusercontent.com/ugc/2064377962739254535/09B0A8D11B1AA84576627FB9BB4663E3D0C2C313/",
			Crann ="http://cloud-3.steamusercontent.com/ugc/2064377962739254636/5A255B7F1A880072A759FD565084B6ABFDB7432A/",
			Dualak ="http://cloud-3.steamusercontent.com/ugc/2064377962739254731/39B09C3173BD729B98D0EAFF571FAAEF780D4C96/",
			Gamam ="http://cloud-3.steamusercontent.com/ugc/2064377962739254820/69650201B8D22E1DA43BD7A09AA56832C1EA3474/",
			Natar ="http://cloud-3.steamusercontent.com/ugc/2064377962739254903/5AC6BFDDAA21F465CAB49A5DCD2D872F28820AB2/",
			Olwyn ="http://cloud-3.steamusercontent.com/ugc/2064377962739255012/F88D0A873C75A76D6146FFFF562727DA74C26ED7/",
			Solad ="http://cloud-3.steamusercontent.com/ugc/2064377962739255078/CC8293A11AA2ED6E94B47E8F256F65585CC38542/",
			Tiryll ="http://cloud-3.steamusercontent.com/ugc/2064377962739255138/93DB22680A4FE3D5FB849D7D3C5EAF5DA010748F/",
			Tork ="http://cloud-3.steamusercontent.com/ugc/2064377962739255202/BB341225C631E5CFEB280744941AC0EA4CAA321A/",
			Wylio ="http://cloud-3.steamusercontent.com/ugc/2064377962739255282/02152CB3502A02EEE60567CC01C6996416BBA4C7/"
		}
	}
}

return C