-- DEVELOPMENT
-- require("vscode/console")

-- MODULES
U = require("lib.utilities")
C = require("kingsdilemma.lib.constants")
O = require("kingsdilemma.lib.objects")
S = require("kingsdilemma.core.state")
L = require("kingsdilemma.core.lighting")
V = require("kingsdilemma.core.voting")

-- gameState Variable Initialization
gameState = {}

-- COMPONENTS
-- require("kingsdilemma.debug")
require("kingsdilemma.hud")
require("kingsdilemma.listeners")